---
- name: Load a variable file based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-dependencies.yaml'
      paths:
        - 'vars'

- name: Install basic dependencies
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - zip
    - tar
    - unzip
    - curl
    - wget

- name: Install PostgreSQL server
  block:
    - name: Install PostgreSQL server for RedHat
      include_tasks: el/main.yaml
      when: ansible_os_family == 'RedHat'
    - name: Install PostgreSQL server for RedHat
      include_tasks: debian/main.yaml
      when: ansible_os_family == 'Debian'

- name: Install Python package manager
  when: update_pg_hba_conf
  include_tasks: python-deps/main.yaml
  
- name: Enable & Start the service
  block: 
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        daemon_reload: yes
        enabled: true
        name: '{{ service_name }}'

- name: Configure PostgreSQL server
  when: update_pg_hba_conf
  include_tasks: post-install/main.yaml
    
- name: Install patroni binary
  when: enabled_postgresql_ha
  include_tasks: patroni/main.yaml
  
- name: Install etcd database
  when: enabled_postgresql_ha
  block:
    - name: Install etcd plugin pip
      when: enabled_postgresql_ha
      include_tasks: etcd/pip-plugin.yaml
    - name: Setup etcd database
      include_tasks: etcd/main.yaml
    - name: Configure firewall for RedHat distribution
      when: ansible_os_family == 'RedHat'
      include_tasks: etcd/firewall-cmd.yaml
    - name: Configure firewall for Debian distribution
      when: ansible_os_family == 'Debian'
      include_tasks: etcd/ufw.yaml