---
- name: Debug variables
  debug:
    msg: '{{ item }}'
  loop:
    - "{{ rpm_repository_url }}"

- name: Install PostgreSQL server for RetHat
  block:
    - name: Install PostgreSQL server for RedHat
      include_tasks: el/main.yaml
      when: ansible_os_family == 'RedHat'
    - name: Install PostgreSQL server for RedHat
      include_tasks: debian/main.yaml
      when: ansible_os_family == 'Debian'

- name: Enable & Start the service
  block: 
    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        enabled: true
        name: 'postgresql-{{ postgres_version }}'

