---
- name: Debug variables
  debug:
    msg: '{{ item }}'
  loop:
    - "{{ rpm_repository_url }}"

- name: Install PostgreSQL server for RetHat
  when: ansible_os_family == 'RedHat' 
  block:
    - name: Add repository
      yum:
        name: "{{ rpm_repository_url }}"
        state: present
        disable_gpg_check: true
    - name: Disable repo for Oracle, RHEL v8
      command:
        cmd: dnf -qy module disable postgresql
      when: ansible_distribution_major_version == '8'
    - name: Install PostgreSQL Server
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - 'postgresql{{ postgres_version }}-server'
    - name: Init database
      command:
        cmd: '/usr/pgsql-{{ postgres_version }}/bin/postgresql-{{ postgres_version }}-setup initdb'

- name: Install PostgreSQL server for Debian
  when: ansible_os_family == 'Debian'
  block:
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main
        state: present
        filename: pgdg.list
    - name: Add apt-key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /etc/apt/keyrings/pgdg.asc
    - name: Update repositories cache and install "postgresql" package
      ansible.builtin.apt:
        name: postgresql-{{ postgres_version }}
        update_cache: yes

- name: Enable & Start the service
  block: 
    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        enabled: true
        name: 'postgresql-{{ postgres_version }}'

