- name: Add repository
  yum:
    name: "{{ rpm_repository_url }}"
    state: present
    disable_gpg_check: true
- name: Disable repo for Oracle, RHEL v8
  command:
    cmd: dnf -qy module disable postgresql
  when: ansible_distribution_major_version | int >= 8
- name: Install depedency for postgresql-devel
  yum: 
    name: "{{ item }}"
    state: present
  loop: "{{ dependencies }}"
- name: Install PostgreSQL Server
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - 'postgresql{{ postgres_version }}-server'
    - 'postgresql{{ postgres_version }}-devel'
- name: Check file postgresql.conf is exists
  stat:
    path: "{{ postgres_data_dir }}/postgresql.conf"
  register: pg_init
- name: Init database
  command:
    cmd: '/usr/pgsql-{{ postgres_version }}/bin/postgresql-{{ postgres_version }}-setup initdb'
  when: not pg_init.stat.exists
- name: Expose port {{ postgres_port }}/tcp with firewall-cmd
  ansible.posix.firewalld:
    port: "{{ postgres_port }}/tcp"
    permanent: true
    zone: public
    state: enabled
    immediate: true