- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main
    state: present
    filename: pgdg.list
- name: Add apt-key
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/keyrings/pgdg.asc
- name: Update repositories cache and install "postgresql" package
  ansible.builtin.apt:
    name: postgresql-{{ postgres_version }}
    update_cache: yes