- name: Install python package manager
  package:
    name: python3-pip
    state: present
- name: Update pip engine from pip3 
  command:
    cmd: pip3 install --upgrade pip
- name: Check pip version
  register: pip_version
  command:
    cmd: "{{ pip_executeable }} --version"
- name: debug pip version
  debug:
    msg: "{{ pip_version.stdout }}"
- name: Install default package
  pip:
    executable: "{{ pip_executeable }}"
    name: "{{ item }}"
    state: present
  loop:
    - psycopg
    - psycopg2-binary
    - urllib3